### ISSUE TITLE
Goed gebruik stylesheet, nog een keer in jouw styles folder zetten is niet nodig

### ISSUE THREAD

**Issue by lisagjh** [julia-stevens/look-and-feel-corporate-identity#25]
https://github.com/julia-stevens/look-and-feel-corporate-identity/blob/5a8e107daeb1bbc0325763f03e2aea97f930c4c0/index.html#L8

Goed dat je de stylesheet hebt gelinked. 

https://github.com/julia-stevens/look-and-feel-corporate-identity/blob/main/styles/stylesheet.css#L28

Maaar waarom heb je hem ook in je eigen files gezet? Als je hem goed gelinked hebt is dit niet nodig. 

https://github.com/julia-stevens/look-and-feel-corporate-identity/blob/5a8e107daeb1bbc0325763f03e2aea97f930c4c0/index.html#L14-L15

Je past de classes wel erg goed toe in jouw html! Verder ziet je code er erg netjes uit, je CSS en JS is erg duidelijk en overzichtelijk.

**Comment by julia-stevens** [comment]
**Commit:** [af5c749](https://github.com/julia-stevens/look-and-feel-corporate-identity/commit/af5c749d611fa299b0b41264af434f41f97238a0)

Ik had de locale kopie van de stylesheet nog in mijn /styles map staan, deze heb ik verwijderd.
