### ISSUE TITLE
Code review - Dubbele CSS classes

### ISSUE THREAD

**Issue by kimnikitaschijf** [julia-stevens/look-and-feel-corporate-identity#26]
Je hebt op meerdere plekken de `ease-in-out` transition. Misschien kan je hier 1 class van maken of dit toevoegen aan bestaande classes. 

Verder is alles goed zover wij het hebben gezien!

@Mikiyas-hs

**Comment by julia-stevens** [comment]
Achteraf heb ik een aantal transitions aangepast, waardoor er weinig overkoepelende meer zijn. Hierdoor heeft het maken van een gezamenlijke class niet echt een toegevoegde waarde.
